# Generated by Django 5.2.12 on 2026-03-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPANY', 'Company Owner'), ('GUIDE', 'Guide'), ('FINANCE', 'Finance'), ('SUPPORT', 'Support'), ('PILGRIM', 'Pilgrim')], max_length=30),
        ),
    ]
