# Generated by Django 5.2.12 on 2026-03-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COMPANY', 'Company Owner'), ('GUIDE', 'Guide'), ('FINANCE', 'Finance'), ('SUPPORT', 'Support'), ('PILGRIM', 'Pilgrim')], max_length=30),
        ),
    ]
