# Generated by Django 5.2.12 on 2026-03-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('package_type', models.CharField(choices=[('family', 'Family'), ('individual', 'Individual'), ('vip', 'VIP')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('includes_flight', models.BooleanField(default=False)),
                ('includes_hotel', models.BooleanField(default=False)),
                ('includes_transportation', models.BooleanField(default=False)),
                ('includes_meals', models.BooleanField(default=False)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('hotel_stars', models.PositiveIntegerField(blank=True, null=True)),
                ('hotel_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='companies.company')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
