# Generated by Django 5.2.12 on 2026-03-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='available_seats',
        ),
    ]
