# Generated by Django 5.2.12 on 2026-03-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_package_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
