# Generated by Django 5.2.12 on 2026-03-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='company/qr/')),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='company/docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_PAYMENT', 'Waiting Payment'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
