# Generated by Django 5.2.12 on 2026-03-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='description',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='company',
            name='commission_rate',
        ),
        migrations.AddField(
            model_name='company',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/docs/'),
        ),
        migrations.AddField(
            model_name='company',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=12121, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/qr/'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_PAYMENT', 'Waiting Payment'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
    ]
