# Generated by Django 5.2.12 on 2026-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_rename_description_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
