# Generated by Django 5.2.12 on 2026-03-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_financialprofile_supportprofile_touristguideprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='companies.company'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='companies.company'),
        ),
        migrations.AddField(
            model_name='touristguideprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='companies.company'),
        ),
    ]
