# Generated by Django 5.2.12 on 2026-03-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_financialprofile_company_supportprofile_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supportprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='touristguideprofile',
            name='company',
        ),
    ]
